# Generated by Django 5.2.3 on 2025-06-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OlfactoryFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OlfactoryNoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('show_in_filters', models.BooleanField(default=False, verbose_name='Show in filters section')),
                ('show_in_fragrances', models.BooleanField(default=False, verbose_name='Show in Fragrances dropdown')),
                ('filter_name', models.CharField(blank=True, max_length=50, verbose_name='Filter name (if different from category)')),
                ('filter_slug', models.SlugField(blank=True, verbose_name='Filter slug (for frontend)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('show_in_fragrances', models.BooleanField(default=False, verbose_name='Show in Fragrances dropdown')),
                ('olfactory_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main.olfactoryfamily')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='OlfactoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.olfactorynotecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('detail_media', models.FileField(blank=True, help_text='Upload an image or video for the detail page', upload_to='products/media/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True, help_text='История создания парфюма')),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_on_hero', models.BooleanField(default=False, verbose_name='Show in hero section (plus button)')),
                ('show_in_featured', models.BooleanField(default=False, verbose_name='Show in featured products section')),
                ('show_in_best_sellers', models.BooleanField(default=False, verbose_name='Show in best sellers section')),
                ('base_notes', models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Base'}, related_name='base_notes', to='main.olfactorynote')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='main.category')),
                ('middle_notes', models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Middle'}, related_name='middle_notes', to='main.olfactorynote')),
                ('olfactory_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='main.olfactoryfamily')),
                ('top_notes', models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Top'}, related_name='top_notes', to='main.olfactorynote')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.capacity')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfume')),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='capacities',
            field=models.ManyToManyField(blank=True, related_name='perfumes', through='main.PerfumeCapacity', to='main.capacity'),
        ),
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.perfume')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='main_catego_name_5111b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='perfumecapacity',
            unique_together={('perfume', 'capacity')},
        ),
    ]
